export const WORKOUT_ERRORS = {
  INVALID_REPS: 'INVALID_REPS',
  MISSING_SETS: 'MISSING_SETS',
  INVALID_WEIGHT: 'INVALID_WEIGHT',
  MISSING_SET_NUMBER: 'MISSING_SET_NUMBER',
  EXERCISE_NOT_FOUND: 'EXERCISE_NOT_FOUND',
};
